# Generated by Django 3.1 on 2020-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_perfil_contatos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contatos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contato',
            field=models.ManyToManyField(related_name='_perfil_contato_+', to='Perfil.Perfil'),
        ),
    ]
