# Generated by Django 3.1 on 2020-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0004_auto_20201008_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contato',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='_perfil_contatos_+', to='Perfil.Perfil'),
        ),
    ]
